[package]
name = "uffd"
version = "0.1.0"
edition = "2024"

[dependencies]
libc = "0.2.178"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
userfaultfd = "0.9.0"
vmm-sys-util = "0.15.0"
